wip

diff --git a/env_setup/cloudbuild.provision.yaml b/env_setup/cloudbuild.provision.yaml
--- a/env_setup/cloudbuild.provision.yaml
+++ b/env_setup/cloudbuild.provision.yaml
@@ -100,16 +100,33 @@ steps:
   - id: 'Config Kueue'
     name: gcr.io/google.com/cloudsdktool/cloud-sdk 
     entrypoint: /bin/bash
-    dir: kueue
     args:
       - -c
       - |
         curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
         mv kustomize /usr/local/bin
+        cd kueue
         kustomize edit set namespace $_NAMESPACE
         kustomize edit remove configmap tpu-config
         kustomize edit add configmap tpu-config --from-literal=NAME=$_TPU_TYPE --from-literal=NUM_OF_CHIPS=$_NUM_OF_CHIPS
-        kustomize build . | kubectl apply -f - 
+        
+        max_attempts=5
+        attempt_num=1
+        success=false
+
+        while [ $success = false ] && [ $attempt_num -le $max_attempts ]; do
+          echo Sleep for a few seconds to avoid timeouts from Kueue
+          sleep 10
+          echo Attempting deployment of Kueue CRDs
+          kubectl apply -k .
+          if [ $? -eq 0 ]; then
+            success=true
+            echo Deployment of CRDs successful
+          else
+            echo "Deployment of CRDs faile"
+            attempt_num=$(( attempt_num + 1 ))
+          fi
+        done
 
 
 
